# Form implementation generated from reading ui file 'e:\GIT_pros\CrawlerPractice2\UI\main.ui'
#
# Created by: PyQt5 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(696, 499)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_danbooru = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_danbooru.setObjectName("label_danbooru")
        self.horizontalLayout.addWidget(self.label_danbooru)
        self.PB_danbooru_gallery = QtWidgets.QPushButton(parent=self.centralwidget)
        self.PB_danbooru_gallery.setObjectName("PB_danbooru_gallery")
        self.horizontalLayout.addWidget(self.PB_danbooru_gallery)
        self.PB_danbooru_post = QtWidgets.QPushButton(parent=self.centralwidget)
        self.PB_danbooru_post.setObjectName("PB_danbooru_post")
        self.horizontalLayout.addWidget(self.PB_danbooru_post)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.TE_log = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.TE_log.setReadOnly(True)
        self.TE_log.setObjectName("TE_log")
        self.verticalLayout.addWidget(self.TE_log)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 696, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CrawlerPractice2"))
        self.label_danbooru.setText(_translate("MainWindow", "danbooru:"))
        self.PB_danbooru_gallery.setText(_translate("MainWindow", "gallery"))
        self.PB_danbooru_post.setText(_translate("MainWindow", "post"))
